# Assignment-4
## UCS420 “Cognitive Computing”
### NumPy-Introduction-1


Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
# a) Addition of 2 in all the element
print(arr + 2)

[3 4 5 6 7]


In [6]:
# b) Multiply 3 with all the elements
print(arr * 3)

[ 3  6  9 12 15]


In [7]:
# c) Divide every element by 2
print(arr / 2)

[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

In [8]:
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [12]:
# b) Find the most frequent value and their indice(s) in the following arrays:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Most Frequent Value in x:", most_frequent)
print("Indices:", indices)

# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most Frequent Value in y:", most_frequent)
print("Indices:", indices)

Most Frequent Value in x: 1
Indices: [0 5 7 8 9]
Most Frequent Value in y: 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:


In [16]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [18]:
# a) Access 1st row, 2nd column
print(arr[0,1])

# b) Access 3rd row, 1st column
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?


In [ ]:
pragun = np.linspace(10, 100, 25)
print(prekshit)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
print("Dimensions:", prekshit.ndim)
print("Shape:", prekshit.shape)
print("Total Elements:", prekshit.size)
print("Data Type:", prekshit.dtype)
print("Total Bytes:", prekshit.nbytes)

Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200


In [ ]:
transpose_array = prekshit.reshape(25, 1)
print(transpose_array)

# Using T attribute
print(prekshit.T)

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<<your_name>>.

In [ ]:
ucs420_prekshit = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

In [ ]:
print(np.mean(ucs420_prekshit))
print(np.median(ucs420_prekshit))
print(np.max(ucs420_prekshit))
print(np.min(ucs420_prekshit))
print(np.unique(ucs420_prekshit))

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
reshaped_ucs420_prekshit = ucs420_prekshit.reshape(4,3)
print(reshaped_ucs420_prekshit)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [ ]:
resized_ucs420_prekshit = np.resize(ucs420_prekshit,(2,3))
print(resized_ucs420_prekshit)

[[10 20 30]
 [40 50 60]]
