# UCS420: Cognitive Computing
### Assignment 6 — Numpy-II

In [ ]:
import numpy as np

Q1. Sensor Readings using NumPy

Consider the following sensor readings:

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

A sensor has an average measurement error of +2°C.

Perform the following without using a for loop:

In [ ]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [ ]:
# a. Add 2°C to every reading using vectorization.
new_temperature = temperature + 2
print(new_temperature)

[27 30 33 37 40 29 35 42]


In [7]:
# b. Convert all temperatures from Celsius to Fahrenheit using:
# F = (9/5)C + 32
fahrenheit = (9/5) * temperature + 32
print(fahrenheit)

[ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]


In [8]:
# c. Identify all readings greater than 32°C using Boolean indexing.
greater_than_32 = temperature[temperature > 32]
print(greater_than_32)

[35 38 33 40]


In [9]:
# d. Count how many readings exceed 32°C.
count = np.sum(temperature > 32)
print(count)

4


In [ ]:
# e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.
# Vectorization lets NumPy perform an operation on the complete array at once instead of writing a for loop for every element.

Q2. Daily Steps Analysis

The following matrix represents the number of daily steps recorded by four users over three days:

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

Perform the following:


In [ ]:
# a. Calculate the total steps recorded.
# b. Calculate the mean number of steps.
# c. Find the maximum and minimum values.
# d. Calculate the total steps for each day using axis=0.
# e. Calculate the total steps for each user using axis=1.
# f. Find the user/day position containing the maximum number of steps using argmax().

In [10]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a) Total steps
print("Total Steps:", np.sum(steps))

# b) Mean steps
print("Mean Steps:", np.mean(steps))

# c) Maximum and minimum
print("Maximum Steps:", np.max(steps))
print("Minimum Steps:", np.min(steps))

# d) Total steps for each day
print("Total Steps for Each Day:", np.sum(steps, axis=0))

# e) Total steps for each user
print("Total Steps for Each User:", np.sum(steps, axis=1))

# f) Position of maximum value
max_index = np.argmax(steps)
position = np.unravel_index(max_index, steps.shape)

print("Position of Maximum Steps:", position)

Total Steps: 84200
Mean Steps: 7016.666666666667
Maximum Steps: 9500
Minimum Steps: 4500
Total Steps for Each Day: [26500 27300 30400]
Total Steps for Each User: [18300 24500 14400 27000]
Position of Maximum Steps: (np.int64(3), np.int64(2))


Q3. NumPy Slicing, Copying, Reshaping and Flattening

Perform the following NumPy operations:

In [ ]:
# a. Create the array:
original = np.array([1, 2, 3, 4, 5, 6])

# b. Create a slice containing elements from index 1 to 4 and store it in subset.
# c. Modify the first element of subset to 999 and display both original and subset.
# d. Create another slice from original using .copy(). Modify its first element to 500 and display the original and copied array.
# e. Create a NumPy array containing numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.
# f. Extract the first row, last row, second column, and elements from rows 1–2 and columns 2–3.
# g. Create flattened versions using both flatten() and ravel().
# h. Modify an element in the array returned by ravel() and observe whether the original matrix is affected.
# i. Modify an element in the array returned by flatten() and observe whether the original matrix is affected.
# j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [11]:
# a) Original array
original = np.array([1, 2, 3, 4, 5, 6])
print("Original Array:", original)

# b) Slice from index 1 to 4
subset = original[1:5]
print("Subset:", subset)

# c) Modify first element of subset
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)

# d) Create a copy
copied_array = original[1:5].copy()
copied_array[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied Array:", copied_array)

# e) Create and reshape array
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)

# f) Indexing and slicing
print("\nFirst Row:", matrix[0])
print("Last Row:", matrix[-1])
print("Second Column:", matrix[:, 1])

print("Rows 1-2 and Columns 2-3:")
print(matrix[0:2, 1:3])

# g) flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nFlattened Array:", flattened)
print("Raveled Array:", raveled)

# h) Modify ravel()
raveled[0] = 100

print("\nAfter modifying ravel():")
print("Raveled:", raveled)
print("Original Matrix:")
print(matrix)

# i) Modify flatten()
flattened[1] = 200

print("\nAfter modifying flatten():")
print("Flattened:", flattened)
print("Original Matrix:")
print(matrix)

# j) Array properties
print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

Original Array: [1 2 3 4 5 6]
Subset: [2 3 4 5]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied Array: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row: [1 2 3 4]
Last Row: [ 9 10 11 12]
Second Column: [ 2  6 10]
Rows 1-2 and Columns 2-3:
[[2 3]
 [6 7]]

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel():
Raveled: [100   2   3   4   5   6   7   8   9  10  11  12]
Original Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After modifying flatten():
Flattened: [  1 200   3   4   5   6   7   8   9  10  11  12]
Original Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data Type: int64


## Q4. Cognitive-Assistive System using Ordinary Least Squares

A cognitive-assistive system wants to predict a user's assistance score based on three factors:

* Sleep hours
* Activity level
* Stress level

Consider:

```python
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])
```

Each row represents one user and each column represents a feature.

Perform the following:

a. Display the shape and dimensions of `X`.
b. Calculate `X.T` and explain what the transpose represents.
c. Calculate the matrix product `X.T @ X`.
d. Calculate the matrix inverse using `np.linalg.inv()` where appropriate.
e. Implement the Ordinary Least Squares equation:

**β = (XᵀX)⁻¹Xᵀy**

f. Explain what the resulting coefficients represent in the context of the three user features.
g. For a new user:

`new_user = np.array([5, 40, 7])`

use the calculated coefficients to obtain the predicted assistance score.


In [13]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a) Shape and dimensions
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

# b) Transpose
XT = X.T

print("\nTranspose of X:")
print(XT)

# c) X.T @ X
XTX = XT @ X

print("\nX.T @ X:")
print(XTX)

# d) Inverse
XTX_inverse = np.linalg.inv(XTX)

print("\nInverse of X.T @ X:")
print(XTX_inverse)

# e) Ordinary Least Squares
beta = XTX_inverse @ XT @ y

print("\nCoefficients (Beta):")
print(beta)

# f) The three coefficients represent the estimated contribution of sleep hours, activity level, and stress level to the predicted assistance score.
#The calculated coefficients are approximately:

#* Sleep hours: -0.159
#* Activity level: 0.141
#* Stress level: 10.063

#This means that, according to this fitted model, the stress-level feature has the strongest positive contribution to the assistance score, while the sleep-hours coefficient is slightly negative. These coefficients describe the mathematical relationship learned from the given four observations.

 # g) Prediction for new user
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nPredicted Assistance Score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Coefficients (Beta):
[-0.15921454  0.14083853 10.06302242]

Predicted Assistance Score: 75.27862544779117
